In [1]:
import pandas as pd
import numpy as np

In [2]:
xtrain=pd.read_csv(r"C:\Users\acer\Desktop\ML\x_train.csv")

In [3]:
xtest=pd.read_csv(r"C:\Users\acer\Desktop\ML\x_test.csv")

In [4]:
ytrain=pd.read_csv(r"C:\Users\acer\Desktop\ML\y_train.csv")

In [5]:
ytest=pd.read_csv(r"C:\Users\acer\Desktop\ML\y_test.csv")

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
xf=xtrain.iloc[:,6:-1]
xt=xtest.iloc[:,6:-1]

In [8]:
xf

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
0,4950,0.0,125,360,1
1,2882,1843.0,123,480,1
2,3000,3416.0,56,180,1
3,9703,0.0,112,360,1
4,2333,2417.0,136,360,1
5,5250,0.0,94,360,1
6,4333,2451.0,110,360,1
7,6125,1625.0,187,480,1
8,2333,1451.0,102,480,0
9,1800,2934.0,93,360,0
10,3500,1667.0,114,360,1
11,8333,3167.0,165,360,1
12,4354,0.0,136,360,1
13,9328,0.0,188,180,1
14,7200,0.0,120,360,1
15,3800,3600.0,216,360,0
16,3593,4266.0,132,180,0
17,3417,1750.0,186,360,1
18,3316,3500.0,88,360,1
19,3399,1640.0,111,180,1
20,2439,3333.0,129,360,1
21,6250,5654.0,188,180,1
22,1000,3022.0,110,360,1
23,4180,2306.0,182,360,1
24,2484,2302.0,137,360,1
25,7787,0.0,240,360,1
26,4583,0.0,133,360,0
27,3406,4417.0,123,360,1
28,11146,0.0,136,360,1
29,5703,0.0,128,360,1
...,...,...,...,...,...
354,6033,0.0,160,360,1
355,4226,1040.0,110,360,1
356,3812,0.0,112,360,1
357,4583,1508.0,128,360,1
358,2600,1700.0,107,360,1
359,3200,2254.0,126,180,0
360,4167,1447.0,158,360,1
361,5391,0.0,130,360,1
362,3366,2200.0,135,360,1
363,10139,0.0,260,360,1
364,10000,0.0,214,360,1
365,3232,1950.0,108,360,1
366,1963,0.0,53,360,1
367,8072,240.0,253,360,1
368,2755,0.0,65,300,1
369,4300,2014.0,194,360,1
370,11757,0.0,187,180,1
371,8334,0.0,160,360,1
372,4342,189.0,124,360,1
373,3500,0.0,81,300,1
374,3814,1483.0,124,300,1
375,3180,0.0,71,360,0
376,2787,1917.0,146,360,0
377,14583,0.0,185,180,1
378,7740,0.0,128,180,1
379,3597,2157.0,119,360,0
380,2583,2167.0,104,360,1
381,5923,2054.0,211,360,1
382,2971,2791.0,144,360,1
383,4583,5625.0,255,360,1

In [9]:
xxf=xf.values.reshape(-1,5)
xxt=xt.values.reshape(-1,5)
yt=ytest.values.reshape(-1,1)
ytar=ytrain.values.reshape(-1,1)

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
mo=KNeighborsClassifier()

In [12]:
ml=mo.fit(xxf,ytar)

C:\Users\acer\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  if __name__ == '__main__':

In [13]:
yp=ml.predict(xxt)

In [14]:
from sklearn.metrics import accuracy_score

In [15]:
acc=accuracy_score(yt,yp)*100

In [16]:
acc

61.458333333333336

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
mx=MinMaxScaler()

In [19]:
xxtrain=mx.fit_transform(xxf)
xxtest=mx.fit_transform(xxt)

C:\Users\acer\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)

In [20]:
mno=KNeighborsClassifier()

In [21]:
mnl=mno.fit(xxtrain,ytar)

C:\Users\acer\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  if __name__ == '__main__':

In [22]:
ypn=mnl.predict(xxtest)

In [23]:
accn=accuracy_score(yt,ypn)*100

In [24]:
accn

75.0

In [25]:
acc_table=pd.DataFrame({"accuracy":[acc,accn]},index=["without preprocessed","with preprocessed"])

In [26]:
acc_table

                       accuracy
without preprocessed  61.458333
with preprocessed     75.000000

In [27]:
ydata=list(yt)

In [28]:
at=pd.DataFrame({"Ya":ydata,"yp":ypn})

In [29]:
at

     Ya yp
0   [N]  Y
1   [Y]  Y
2   [Y]  Y
3   [Y]  Y
4   [Y]  Y
5   [N]  Y
6   [Y]  Y
7   [N]  N
8   [Y]  Y
9   [Y]  Y
10  [N]  N
11  [Y]  N
12  [Y]  Y
13  [N]  N
14  [Y]  Y
15  [Y]  Y
16  [Y]  Y
17  [Y]  Y
18  [Y]  Y
19  [Y]  Y
20  [N]  N
21  [Y]  Y
22  [Y]  N
23  [N]  Y
24  [N]  N
25  [N]  N
26  [N]  N
27  [Y]  Y
28  [Y]  Y
29  [Y]  Y
..  ... ..
66  [N]  Y
67  [N]  N
68  [N]  Y
69  [Y]  Y
70  [Y]  Y
71  [Y]  Y
72  [N]  N
73  [N]  Y
74  [N]  N
75  [N]  Y
76  [Y]  Y
77  [Y]  Y
78  [N]  Y
79  [Y]  Y
80  [Y]  Y
81  [Y]  Y
82  [N]  Y
83  [Y]  Y
84  [N]  Y
85  [Y]  Y
86  [Y]  Y
87  [N]  N
88  [Y]  Y
89  [N]  Y
90  [N]  N
91  [Y]  N
92  [Y]  Y
93  [Y]  Y
94  [Y]  Y
95  [Y]  Y

[96 rows x 2 columns]